// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Blueprint contains a collection of kubernetes resources in the form of
/// YAML files. The file contents of a blueprint are collectively known as
/// package. A blueprint can be
/// a) imported from TNA's public catalog
/// b) modified as per a user's need
/// c) proposed and approved.
/// On approval, a revision of blueprint is created which can be used to
/// create a deployment on Orchestration or Workload Cluster.
public struct Blueprint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the blueprint. If unspecified, the name will be autogenerated
  /// from server side. Name of the blueprint must not contain `@` character.
  public var name: Swift.String = Swift.String()

  /// Output only. Immutable. The revision ID of the blueprint.
  /// A new revision is committed whenever a blueprint is approved.
  public var revisionId: Swift.String = Swift.String()

  /// Required. Immutable. The public blueprint ID from which this blueprint was
  /// created.
  public var sourceBlueprint: Swift.String = Swift.String()

  /// Output only. The timestamp that the revision was created.
  public var revisionCreateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Approval state of the blueprint (DRAFT, PROPOSED, APPROVED)
  public var approvalState: Blueprint.ApprovalState = Blueprint.ApprovalState()

  /// Optional. Human readable name of a Blueprint.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Name of the repository where the blueprint files are stored.
  public var repository: Swift.String = Swift.String()

  /// Optional. Files present in a blueprint.
  /// When invoking UpdateBlueprint API, only the modified files should be
  /// included in this. Files that are not included in the update of a blueprint
  /// will not be changed.
  public var files: [File] = []

  /// Optional. Labels are key-value attributes that can be set on a blueprint
  /// resource by the user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Blueprint creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when the blueprint was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Source provider is the author of a public blueprint, from
  /// which this blueprint is created.
  public var sourceProvider: Swift.String = Swift.String()

  /// Output only. DeploymentLevel of a blueprint signifies where the blueprint
  /// will be applied. e.g. [HYDRATION, SINGLE_DEPLOYMENT, MULTI_DEPLOYMENT]
  public var deploymentLevel: DeploymentLevel = DeploymentLevel()

  /// Output only. Indicates if the deployment created from this blueprint can be
  /// rolled back.
  public var rollbackSupport: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Blueprint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Blueprint().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Approval state indicates the state of a Blueprint in its approval
  /// lifecycle.
  public enum ApprovalState: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// A blueprint starts in DRAFT state once it is created. All edits are made
    /// to the blueprint in DRAFT state.
    case draft
    /// When the edits are ready for review, blueprint can be proposed and moves
    /// to PROPOSED state. Edits cannot be made to a blueprint in PROPOSED state.
    case proposed
    /// When a proposed blueprint is approved, it moves to APPROVED state. A new
    /// revision is committed. The latest committed revision can be used to
    /// create a deployment on Orchestration or Workload Cluster. Edits to an
    /// APPROVED blueprint changes its state back to DRAFT. The last committed
    /// revision of a blueprint represents its latest APPROVED state.
    case approved
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .draft: return 1
      case .proposed: return 2
      case .approved: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "APPROVAL_STATE_UNSPECIFIED"
      case .draft: return "DRAFT"
      case .proposed: return "PROPOSED"
      case .approved: return "APPROVED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "APPROVAL_STATE_UNSPECIFIED": self = .unspecified
      case "DRAFT": self = .draft
      case "PROPOSED": self = .proposed
      case "APPROVED": self = .approved
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .draft
      case 2: self = .proposed
      case 3: self = .approved
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .draft: return try container.encode(1)
      case .proposed: return try container.encode(2)
      case .approved: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.Blueprint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
