// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response object for `ComputeDeploymentStatus`.
public struct ComputeDeploymentStatusResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the deployment.
  public var name: Swift.String = Swift.String()

  /// Output only. Aggregated status of a deployment.
  public var aggregatedStatus: Status = Status()

  /// Output only. Resource level status details in deployments.
  public var resourceStatuses: [ResourceStatus] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeDeploymentStatusResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeDeploymentStatusResponse().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let aggregatedStatus = CodingKeys(stringValue: "aggregatedStatus")
    static let resourceStatuses = CodingKeys(stringValue: "resourceStatuses")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "aggregatedStatus",
      "resourceStatuses",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Status.self, forKey: .aggregatedStatus) {
      self.aggregatedStatus = value
    }
    if let value = try container.decodeIfPresent([ResourceStatus].self, forKey: .resourceStatuses) {
      self.resourceStatuses = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.aggregatedStatus, forKey: .aggregatedStatus)
    try container.encode(self.resourceStatuses, forKey: .resourceStatuses)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.ComputeDeploymentStatusResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
