// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Deployment contains a collection of YAML files (This collection is also known
/// as package) that can to applied on an orchestration cluster (GKE cluster with
/// TNA addons) or a workload cluster.
public struct Deployment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the deployment.
  public var name: Swift.String = Swift.String()

  /// Output only. Immutable. The revision ID of the deployment.
  /// A new revision is committed whenever a change in deployment is applied.
  public var revisionId: Swift.String = Swift.String()

  /// Required. The blueprint revision from which this deployment was created.
  public var sourceBlueprintRevision: Swift.String = Swift.String()

  /// Output only. The timestamp that the revision was created.
  public var revisionCreateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. State of the deployment (DRAFT, APPLIED, DELETING).
  public var state: Deployment.State = Deployment.State()

  /// Optional. Human readable name of a Deployment.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Name of the repository where the deployment package files are
  /// stored.
  public var repository: Swift.String = Swift.String()

  /// Optional. Files present in a deployment.
  /// When invoking UpdateDeployment API, only the modified files should be
  /// included in this. Files that are not included in the update of a deployment
  /// will not be changed.
  public var files: [File] = []

  /// Optional. Labels are key-value attributes that can be set on a deployment
  /// resource by the user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Deployment creation time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the deployment was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Source provider is the author of a public blueprint, from
  /// which this deployment is created.
  public var sourceProvider: Swift.String = Swift.String()

  /// Optional. Immutable. The WorkloadCluster on which to create the Deployment.
  /// This field should only be passed when the deployment_level of the source
  /// blueprint specifies deployments on workload clusters e.g.
  /// WORKLOAD_CLUSTER_DEPLOYMENT.
  public var workloadCluster: Swift.String = Swift.String()

  /// Output only. Attributes to where the deployment can inflict changes. The
  /// value can only be [SINGLE_DEPLOYMENT, MULTI_DEPLOYMENT].
  public var deploymentLevel: DeploymentLevel = DeploymentLevel()

  /// Output only. Indicates if the deployment can be rolled back, exported from
  /// public blueprint.
  public var rollbackSupport: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let revisionId = CodingKeys(stringValue: "revisionId")
    static let sourceBlueprintRevision = CodingKeys(stringValue: "sourceBlueprintRevision")
    static let revisionCreateTime = CodingKeys(stringValue: "revisionCreateTime")
    static let state = CodingKeys(stringValue: "state")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let repository = CodingKeys(stringValue: "repository")
    static let files = CodingKeys(stringValue: "files")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let sourceProvider = CodingKeys(stringValue: "sourceProvider")
    static let workloadCluster = CodingKeys(stringValue: "workloadCluster")
    static let deploymentLevel = CodingKeys(stringValue: "deploymentLevel")
    static let rollbackSupport = CodingKeys(stringValue: "rollbackSupport")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "revisionId",
      "sourceBlueprintRevision",
      "revisionCreateTime",
      "state",
      "displayName",
      "repository",
      "files",
      "labels",
      "createTime",
      "updateTime",
      "sourceProvider",
      "workloadCluster",
      "deploymentLevel",
      "rollbackSupport",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      self.revisionId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceBlueprintRevision)
    {
      self.sourceBlueprintRevision = value
    }
    self.revisionCreateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .revisionCreateTime)
    if let value = try container.decodeIfPresent(Deployment.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
      self.repository = value
    }
    if let value = try container.decodeIfPresent([File].self, forKey: .files) {
      self.files = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceProvider) {
      self.sourceProvider = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workloadCluster) {
      self.workloadCluster = value
    }
    if let value = try container.decodeIfPresent(DeploymentLevel.self, forKey: .deploymentLevel) {
      self.deploymentLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .rollbackSupport) {
      self.rollbackSupport = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.revisionId, forKey: .revisionId)
    try container.encode(self.sourceBlueprintRevision, forKey: .sourceBlueprintRevision)
    try container.encodeIfPresent(self.revisionCreateTime, forKey: .revisionCreateTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.repository, forKey: .repository)
    try container.encode(self.files, forKey: .files)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.sourceProvider, forKey: .sourceProvider)
    try container.encode(self.workloadCluster, forKey: .workloadCluster)
    try container.encode(self.deploymentLevel, forKey: .deploymentLevel)
    try container.encode(self.rollbackSupport, forKey: .rollbackSupport)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// State defines which state the current deployment is in.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// A deployment starts in DRAFT state. All edits are made in DRAFT state. A
    /// deployment opened for editing after applying will be in draft state,
    /// while its prevision revision will be its current applied version.
    case draft
    /// This state means that the contents (YAML files containing kubernetes
    /// resources) of the deployment have been applied to an Orchestration or
    /// Workload Cluster. A revision is created when a deployment is applied.
    /// This revision will represent the latest view of what is applied on the
    /// cluster until the deployment is modified and applied again, which will
    /// create a new revision.
    case applied
    /// A deployment in DELETING state has been marked for deletion. Its
    /// deletion status can be queried using `ComputeDeploymentStatus` API. No
    /// updates are allowed to a deployment in DELETING state.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .draft: return 1
      case .applied: return 2
      case .deleting: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .draft: return "DRAFT"
      case .applied: return "APPLIED"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "DRAFT": self = .draft
      case "APPLIED": self = .applied
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .draft
      case 2: self = .applied
      case 3: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .draft: return try container.encode("DRAFT")
      case .applied: return try container.encode("APPLIED")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.Deployment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
