// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// DeploymentLevel of a blueprint signifies where the blueprint will be
/// applied.
public enum DeploymentLevel: Codable, Equatable, Sendable {
  /// Default unspecified deployment level.
  case unspecified
  /// Blueprints at HYDRATION level cannot be used to create a Deployment
  /// (A user cannot manually initate deployment of these blueprints on
  /// orchestration or workload cluster).
  /// These blueprints stay in a user's private catalog and are configured and
  /// deployed by TNA automation.
  case hydration
  /// Blueprints at SINGLE_DEPLOYMENT level can be
  /// a) Modified in private catalog.
  /// b) Used to create a deployment on orchestration cluster by the user, once
  /// approved.
  case singleDeployment
  /// Blueprints at MULTI_DEPLOYMENT level can be
  /// a) Modified in private catalog.
  /// b) Used to create a deployment on orchestration cluster which will create
  /// further hydrated deployments.
  case multiDeployment
  /// Blueprints at WORKLOAD_CLUSTER_DEPLOYMENT level can be
  /// a) Modified in private catalog.
  /// b) Used to create a deployment on workload cluster by the user, once
  /// approved.
  case workloadClusterDeployment
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .hydration: return 1
    case .singleDeployment: return 2
    case .multiDeployment: return 3
    case .workloadClusterDeployment: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DEPLOYMENT_LEVEL_UNSPECIFIED"
    case .hydration: return "HYDRATION"
    case .singleDeployment: return "SINGLE_DEPLOYMENT"
    case .multiDeployment: return "MULTI_DEPLOYMENT"
    case .workloadClusterDeployment: return "WORKLOAD_CLUSTER_DEPLOYMENT"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DEPLOYMENT_LEVEL_UNSPECIFIED": self = .unspecified
    case "HYDRATION": self = .hydration
    case "SINGLE_DEPLOYMENT": self = .singleDeployment
    case "MULTI_DEPLOYMENT": self = .multiDeployment
    case "WORKLOAD_CLUSTER_DEPLOYMENT": self = .workloadClusterDeployment
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .hydration
    case 2: self = .singleDeployment
    case 3: self = .multiDeployment
    case 4: self = .workloadClusterDeployment
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .hydration: return try container.encode(1)
    case .singleDeployment: return try container.encode(2)
    case .multiDeployment: return try container.encode(3)
    case .workloadClusterDeployment: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
