// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Deployment contains a collection of YAML files (This collection is also known
/// as package) that can to applied on an orchestration cluster (GKE cluster with
/// TNA addons) or a workload cluster.
public struct Deployment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the deployment.
  public var name: Swift.String = Swift.String()

  /// Output only. Immutable. The revision ID of the deployment.
  /// A new revision is committed whenever a change in deployment is applied.
  public var revisionId: Swift.String = Swift.String()

  /// Required. The blueprint revision from which this deployment was created.
  public var sourceBlueprintRevision: Swift.String = Swift.String()

  /// Output only. The timestamp that the revision was created.
  public var revisionCreateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. State of the deployment (DRAFT, APPLIED, DELETING).
  public var state: Deployment.State = Deployment.State()

  /// Optional. Human readable name of a Deployment.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Name of the repository where the deployment package files are
  /// stored.
  public var repository: Swift.String = Swift.String()

  /// Optional. Files present in a deployment.
  /// When invoking UpdateDeployment API, only the modified files should be
  /// included in this. Files that are not included in the update of a deployment
  /// will not be changed.
  public var files: [File] = []

  /// Optional. Labels are key-value attributes that can be set on a deployment
  /// resource by the user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Deployment creation time.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the deployment was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Source provider is the author of a public blueprint, from
  /// which this deployment is created.
  public var sourceProvider: Swift.String = Swift.String()

  /// Optional. Immutable. The WorkloadCluster on which to create the Deployment.
  /// This field should only be passed when the deployment_level of the source
  /// blueprint specifies deployments on workload clusters e.g.
  /// WORKLOAD_CLUSTER_DEPLOYMENT.
  public var workloadCluster: Swift.String = Swift.String()

  /// Output only. Attributes to where the deployment can inflict changes. The
  /// value can only be [SINGLE_DEPLOYMENT, MULTI_DEPLOYMENT].
  public var deploymentLevel: DeploymentLevel = DeploymentLevel()

  /// Output only. Indicates if the deployment can be rolled back, exported from
  /// public blueprint.
  public var rollbackSupport: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State defines which state the current deployment is in.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// A deployment starts in DRAFT state. All edits are made in DRAFT state. A
    /// deployment opened for editing after applying will be in draft state,
    /// while its prevision revision will be its current applied version.
    case draft
    /// This state means that the contents (YAML files containing kubernetes
    /// resources) of the deployment have been applied to an Orchestration or
    /// Workload Cluster. A revision is created when a deployment is applied.
    /// This revision will represent the latest view of what is applied on the
    /// cluster until the deployment is modified and applied again, which will
    /// create a new revision.
    case applied
    /// A deployment in DELETING state has been marked for deletion. Its
    /// deletion status can be queried using `ComputeDeploymentStatus` API. No
    /// updates are allowed to a deployment in DELETING state.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .draft: return 1
      case .applied: return 2
      case .deleting: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .draft: return "DRAFT"
      case .applied: return "APPLIED"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "DRAFT": self = .draft
      case "APPLIED": self = .applied
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .draft
      case 2: self = .applied
      case 3: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .draft: return try container.encode(1)
      case .applied: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.Deployment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
