// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// File represents a yaml file present in a blueprint's package.
public struct File: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Path of the file in package.
  /// e.g. `gdce/v1/cluster.yaml`
  public var path: Swift.String = Swift.String()

  /// Optional. The contents of a file in string format.
  public var content: Swift.String = Swift.String()

  /// Optional. Signifies whether a file is marked for deletion.
  public var deleted: Swift.Bool = Swift.Bool()

  /// Optional. Indicates whether changes are allowed to a file. If the field is
  /// not set, the file cannot be edited.
  public var editable: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `File`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = File().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let path = CodingKeys(stringValue: "path")
    static let content = CodingKeys(stringValue: "content")
    static let deleted = CodingKeys(stringValue: "deleted")
    static let editable = CodingKeys(stringValue: "editable")

    static let _knownKeys: Set<Swift.String> = [
      "path",
      "content",
      "deleted",
      "editable",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .content) {
      self.content = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deleted) {
      self.deleted = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .editable) {
      self.editable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.content, forKey: .content)
    try container.encode(self.deleted, forKey: .deleted)
    try container.encode(self.editable, forKey: .editable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.File"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
