// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request object for `ListDeployments`.
public struct ListDeploymentsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of parent orchestration cluster resource.
  /// Format should be -
  /// "projects/{project_id}/locations/{location_name}/orchestrationClusters/{orchestration_cluster}".
  public var parent: Swift.String = Swift.String()

  /// Optional. Filtering only supports equality on deployment state.
  /// It should be in the form: "state = DRAFT". `OR` operator can be used to
  /// get response for multiple states. e.g. "state = DRAFT OR state = APPLIED".
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of deployments to return per page.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token, received from a previous ListDeployments call.
  /// It can be provided to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListDeploymentsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDeploymentsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.ListDeploymentsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
