// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request object for `ListHydratedDeployments`.
public struct ListHydratedDeploymentsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The deployment managing the hydrated deployments.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of hydrated deployments to return. The service
  /// may return fewer than this value. If unspecified, at most 50 hydrated
  /// deployments will be returned. The maximum value is 1000. Values above 1000
  /// will be set to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token, received from a previous ListHydratedDeployments
  /// call. Provide this to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListHydratedDeploymentsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListHydratedDeploymentsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.ListHydratedDeploymentsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
