// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration of the cluster management
public struct ManagementConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The configuration can be one of StandardManagementConfig
  /// and FullManagementConfig
  public var oneofConfig: OneOf_OneofConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ManagementConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ManagementConfig().with { $0.standardManagementConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let standardManagementConfig = CodingKeys(stringValue: "standardManagementConfig")
    static let fullManagementConfig = CodingKeys(stringValue: "fullManagementConfig")

    static let _knownKeys: Set<Swift.String> = [
      "standardManagementConfig",
      "fullManagementConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var oneofConfig: OneOf_OneofConfig? = nil
    let oneofConfigCheckAndSet = {
      if oneofConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'oneofConfig'"))
      }
      oneofConfig = $0
    }
    if let standardManagementConfig = try container.decodeIfPresent(
      StandardManagementConfig?.self, forKey: .standardManagementConfig)
    {
      try oneofConfigCheckAndSet(.standardManagementConfig(standardManagementConfig))
    }
    if let fullManagementConfig = try container.decodeIfPresent(
      FullManagementConfig?.self, forKey: .fullManagementConfig)
    {
      try oneofConfigCheckAndSet(.fullManagementConfig(fullManagementConfig))
    }
    self.oneofConfig = oneofConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.oneofConfig {
      switch choice {
      case .standardManagementConfig(let value):
        try container.encode(value, forKey: .standardManagementConfig)
      case .fullManagementConfig(let value):
        try container.encode(value, forKey: .fullManagementConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The configuration can be one of StandardManagementConfig
  /// and FullManagementConfig
  public enum OneOf_OneofConfig: Codable, Equatable, Sendable {
    /// Configuration of the standard (GKE) cluster management
    indirect case standardManagementConfig(StandardManagementConfig?)
    /// Configuration of the full (Autopilot) cluster management. Full cluster
    /// management is a preview feature.
    indirect case fullManagementConfig(FullManagementConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.ManagementConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
