// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Deployment status of NFDeploy.
public struct NFDeployStatus: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Total number of NFs targeted by this deployment
  public var targetedNfs: Swift.Int32 = Swift.Int32()

  /// Output only. Total number of NFs targeted by this deployment with a Ready
  /// Condition set.
  public var readyNfs: Swift.Int32 = Swift.Int32()

  /// Output only. Per-Site Status.
  public var sites: [NFDeploySiteStatus] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `NFDeployStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NFDeployStatus().with { $0.targetedNfs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let targetedNfs = CodingKeys(stringValue: "targetedNfs")
    static let readyNfs = CodingKeys(stringValue: "readyNfs")
    static let sites = CodingKeys(stringValue: "sites")

    static let _knownKeys: Set<Swift.String> = [
      "targetedNfs",
      "readyNfs",
      "sites",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .targetedNfs) {
      self.targetedNfs = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .readyNfs) {
      self.readyNfs = value
    }
    if let value = try container.decodeIfPresent([NFDeploySiteStatus].self, forKey: .sites) {
      self.sites = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetedNfs, forKey: .targetedNfs)
    try container.encode(self.readyNfs, forKey: .readyNfs)
    try container.encode(self.sites, forKey: .sites)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.NFDeployStatus"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
