// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A Blueprint contains a collection of kubernetes resources in the form of
/// YAML files. The file contents of a blueprint are collectively known as
/// package.
/// Public blueprint is a TNA provided blueprint that in present in TNA's public
/// catalog. A user can copy the public blueprint to their private catalog for
/// further modifications.
public struct PublicBlueprint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the public blueprint.
  public var name: Swift.String = Swift.String()

  /// The display name of the public blueprint.
  public var displayName: Swift.String = Swift.String()

  /// The description of the public blueprint.
  public var description: Swift.String = Swift.String()

  /// DeploymentLevel of a blueprint signifies where the blueprint will be
  /// applied. e.g. [HYDRATION, SINGLE_DEPLOYMENT, MULTI_DEPLOYMENT]
  public var deploymentLevel: DeploymentLevel = DeploymentLevel()

  /// Source provider is the author of a public blueprint. e.g. Google, vendors
  public var sourceProvider: Swift.String = Swift.String()

  /// Output only. Indicates if the deployment created from this blueprint can be
  /// rolled back.
  public var rollbackSupport: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PublicBlueprint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PublicBlueprint().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let deploymentLevel = CodingKeys(stringValue: "deploymentLevel")
    static let sourceProvider = CodingKeys(stringValue: "sourceProvider")
    static let rollbackSupport = CodingKeys(stringValue: "rollbackSupport")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "deploymentLevel",
      "sourceProvider",
      "rollbackSupport",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(DeploymentLevel.self, forKey: .deploymentLevel) {
      self.deploymentLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceProvider) {
      self.sourceProvider = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .rollbackSupport) {
      self.rollbackSupport = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.deploymentLevel, forKey: .deploymentLevel)
    try container.encode(self.sourceProvider, forKey: .sourceProvider)
    try container.encode(self.rollbackSupport, forKey: .rollbackSupport)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.PublicBlueprint"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
