// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Blueprint contains a collection of kubernetes resources in the form of
/// YAML files. The file contents of a blueprint are collectively known as
/// package.
/// Public blueprint is a TNA provided blueprint that in present in TNA's public
/// catalog. A user can copy the public blueprint to their private catalog for
/// further modifications.
public struct PublicBlueprint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the public blueprint.
  public var name: Swift.String = Swift.String()

  /// The display name of the public blueprint.
  public var displayName: Swift.String = Swift.String()

  /// The description of the public blueprint.
  public var description: Swift.String = Swift.String()

  /// DeploymentLevel of a blueprint signifies where the blueprint will be
  /// applied. e.g. [HYDRATION, SINGLE_DEPLOYMENT, MULTI_DEPLOYMENT]
  public var deploymentLevel: DeploymentLevel = DeploymentLevel()

  /// Source provider is the author of a public blueprint. e.g. Google, vendors
  public var sourceProvider: Swift.String = Swift.String()

  /// Output only. Indicates if the deployment created from this blueprint can be
  /// rolled back.
  public var rollbackSupport: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `PublicBlueprint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PublicBlueprint().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.PublicBlueprint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
