// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Status of a deployment resource.
public struct ResourceStatus: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the resource.
  public var name: Swift.String = Swift.String()

  /// Namespace of the resource.
  public var resourceNamespace: Swift.String = Swift.String()

  /// Group to which the resource belongs to.
  public var group: Swift.String = Swift.String()

  /// Version of the resource.
  public var version: Swift.String = Swift.String()

  /// Kind of the resource.
  public var kind: Swift.String = Swift.String()

  /// Output only. Resource type.
  public var resourceType: ResourceType = ResourceType()

  /// Output only. Status of the resource.
  public var status: Status = Status()

  /// Output only. Detailed status of NFDeploy.
  public var nfDeployStatus: NFDeployStatus? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceStatus().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resourceNamespace = CodingKeys(stringValue: "resourceNamespace")
    static let group = CodingKeys(stringValue: "group")
    static let version = CodingKeys(stringValue: "version")
    static let kind = CodingKeys(stringValue: "kind")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let status = CodingKeys(stringValue: "status")
    static let nfDeployStatus = CodingKeys(stringValue: "nfDeployStatus")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resourceNamespace",
      "group",
      "version",
      "kind",
      "resourceType",
      "status",
      "nfDeployStatus",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceNamespace) {
      self.resourceNamespace = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .group) {
      self.group = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
      self.kind = value
    }
    if let value = try container.decodeIfPresent(ResourceType.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Status.self, forKey: .status) {
      self.status = value
    }
    self.nfDeployStatus = try container.decodeIfPresent(
      NFDeployStatus.self, forKey: .nfDeployStatus)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resourceNamespace, forKey: .resourceNamespace)
    try container.encode(self.group, forKey: .group)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.kind, forKey: .kind)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.status, forKey: .status)
    try container.encodeIfPresent(self.nfDeployStatus, forKey: .nfDeployStatus)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.ResourceStatus"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
