// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// SiteVersion Hydration is targeting.
public struct SiteVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. NF vendor.
  public var nfVendor: Swift.String = Swift.String()

  /// Output only. NF vendor type.
  public var nfType: Swift.String = Swift.String()

  /// Output only. NF version.
  public var nfVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SiteVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SiteVersion().with { $0.nfVendor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let nfVendor = CodingKeys(stringValue: "nfVendor")
    static let nfType = CodingKeys(stringValue: "nfType")
    static let nfVersion = CodingKeys(stringValue: "nfVersion")

    static let _knownKeys: Set<Swift.String> = [
      "nfVendor",
      "nfType",
      "nfVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nfVendor) {
      self.nfVendor = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nfType) {
      self.nfType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nfVersion) {
      self.nfVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.nfVendor, forKey: .nfVendor)
    try container.encode(self.nfType, forKey: .nfType)
    try container.encode(self.nfVersion, forKey: .nfVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.SiteVersion"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
