// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration of the standard (GKE) cluster management.
public struct StandardManagementConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Name of the VPC Network to put the GKE cluster and nodes in. The
  /// VPC will be created if it doesn't exist.
  public var network: Swift.String = Swift.String()

  /// Optional. Specifies the subnet that the interface will be part of. Network
  /// key must be specified and the subnet must be a subnetwork of the specified
  /// network.
  public var subnet: Swift.String = Swift.String()

  /// Optional. The /28 network that the masters will use. It should be free
  /// within the network.
  public var masterIpv4CidrBlock: Swift.String = Swift.String()

  /// Optional. The IP address range for the cluster pod IPs. Set to blank to
  /// have a range chosen with the default size. Set to /netmask (e.g. /14) to
  /// have a range chosen with a specific netmask. Set to a CIDR notation
  /// (e.g. 10.96.0.0/14) from the RFC-1918 private networks (e.g. 10.0.0.0/8,
  /// 172.16.0.0/12, 192.168.0.0/16) to pick a specific range to use.
  public var clusterCidrBlock: Swift.String = Swift.String()

  /// Optional. The IP address range for the cluster service IPs. Set to blank to
  /// have a range chosen with the default size. Set to /netmask (e.g. /14) to
  /// have a range chosen with a specific netmask. Set to a CIDR notation (e.g.
  /// 10.96.0.0/14) from the RFC-1918 private networks (e.g. 10.0.0.0/8,
  /// 172.16.0.0/12, 192.168.0.0/16) to pick a specific range to use.
  public var servicesCidrBlock: Swift.String = Swift.String()

  /// Optional. The name of the existing secondary range in the cluster's
  /// subnetwork to use for pod IP addresses. Alternatively, cluster_cidr_block
  /// can be used to automatically create a GKE-managed one.
  public var clusterNamedRange: Swift.String = Swift.String()

  /// Optional. The name of the existing secondary range in the cluster's
  /// subnetwork to use for service ClusterIPs. Alternatively,
  /// services_cidr_block can be used to automatically create a GKE-managed one.
  public var servicesNamedRange: Swift.String = Swift.String()

  /// Optional. Master Authorized Network that supports multiple CIDR blocks.
  /// Allows access to the k8s master from multiple blocks. It cannot be set at
  /// the same time with the field man_block.
  public var masterAuthorizedNetworksConfig: MasterAuthorizedNetworksConfig? = nil

  /// Initialize a new instance of `StandardManagementConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StandardManagementConfig().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.telcoautomation.v1.StandardManagementConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
