// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Status of an entity (resource, deployment).
public enum Status: Codable, Equatable, Sendable {
  /// Unknown state.
  case unspecified
  /// Under progress.
  case inProgress
  /// Running and ready to serve traffic.
  case active
  /// Failed or stalled.
  case failed
  /// Delete in progress.
  case deleting
  /// Deleted deployment.
  case deleted
  /// NFDeploy specific status. Peering in progress.
  case peering
  /// K8s objects such as NetworkAttachmentDefinition don't have a defined
  /// status.
  case notApplicable
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .inProgress: return 1
    case .active: return 2
    case .failed: return 3
    case .deleting: return 4
    case .deleted: return 5
    case .peering: return 10
    case .notApplicable: return 11
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .unspecified: return "STATUS_UNSPECIFIED"
    case .inProgress: return "STATUS_IN_PROGRESS"
    case .active: return "STATUS_ACTIVE"
    case .failed: return "STATUS_FAILED"
    case .deleting: return "STATUS_DELETING"
    case .deleted: return "STATUS_DELETED"
    case .peering: return "STATUS_PEERING"
    case .notApplicable: return "STATUS_NOT_APPLICABLE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "STATUS_UNSPECIFIED": self = .unspecified
    case "STATUS_IN_PROGRESS": self = .inProgress
    case "STATUS_ACTIVE": self = .active
    case "STATUS_FAILED": self = .failed
    case "STATUS_DELETING": self = .deleting
    case "STATUS_DELETED": self = .deleted
    case "STATUS_PEERING": self = .peering
    case "STATUS_NOT_APPLICABLE": self = .notApplicable
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .inProgress
    case 2: self = .active
    case 3: self = .failed
    case 4: self = .deleting
    case 5: self = .deleted
    case 10: self = .peering
    case 11: self = .notApplicable
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .inProgress: return try container.encode(1)
    case .active: return try container.encode(2)
    case .failed: return try container.encode(3)
    case .deleting: return try container.encode(4)
    case .deleted: return try container.encode(5)
    case .peering: return try container.encode(10)
    case .notApplicable: return try container.encode(11)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
