// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol TelcoAutomationStub: Sendable {
    func listOrchestrationClusters(
      request: ListOrchestrationClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListOrchestrationClustersResponse

    func getOrchestrationCluster(
      request: GetOrchestrationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.OrchestrationCluster

    func createOrchestrationCluster(
      request: CreateOrchestrationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOrchestrationCluster(
      request: DeleteOrchestrationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listEdgeSlms(
      request: ListEdgeSlmsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListEdgeSlmsResponse

    func getEdgeSlm(
      request: GetEdgeSlmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.EdgeSlm

    func createEdgeSlm(
      request: CreateEdgeSlmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEdgeSlm(
      request: DeleteEdgeSlmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBlueprint(
      request: CreateBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint

    func updateBlueprint(
      request: UpdateBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint

    func getBlueprint(
      request: GetBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint

    func deleteBlueprint(
      request: DeleteBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listBlueprints(
      request: ListBlueprintsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListBlueprintsResponse

    func approveBlueprint(
      request: ApproveBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint

    func proposeBlueprint(
      request: ProposeBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint

    func rejectBlueprint(
      request: RejectBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint

    func listBlueprintRevisions(
      request: ListBlueprintRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListBlueprintRevisionsResponse

    func searchBlueprintRevisions(
      request: SearchBlueprintRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.SearchBlueprintRevisionsResponse

    func searchDeploymentRevisions(
      request: SearchDeploymentRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.SearchDeploymentRevisionsResponse

    func discardBlueprintChanges(
      request: DiscardBlueprintChangesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.DiscardBlueprintChangesResponse

    func listPublicBlueprints(
      request: ListPublicBlueprintsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListPublicBlueprintsResponse

    func getPublicBlueprint(
      request: GetPublicBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.PublicBlueprint

    func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment

    func updateDeployment(
      request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment

    func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment

    func removeDeployment(
      request: RemoveDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListDeploymentsResponse

    func listDeploymentRevisions(
      request: ListDeploymentRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListDeploymentRevisionsResponse

    func discardDeploymentChanges(
      request: DiscardDeploymentChangesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.DiscardDeploymentChangesResponse

    func applyDeployment(
      request: ApplyDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment

    func computeDeploymentStatus(
      request: ComputeDeploymentStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ComputeDeploymentStatusResponse

    func rollbackDeployment(
      request: RollbackDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment

    func getHydratedDeployment(
      request: GetHydratedDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.HydratedDeployment

    func listHydratedDeployments(
      request: ListHydratedDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListHydratedDeploymentsResponse

    func updateHydratedDeployment(
      request: UpdateHydratedDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.HydratedDeployment

    func applyHydratedDeployment(
      request: ApplyHydratedDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.HydratedDeployment

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
