// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class TelcoAutomationLogging: TelcoAutomationStub {
    let inner: any TelcoAutomationStub
    let logger: Logger

    public init(_ inner: any TelcoAutomationStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-telcoautomation-v1"
      logger[metadataKey: "gcp.client.service"] = "telcoautomation"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TelcoAutomation"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listOrchestrationClusters(
      request: ListOrchestrationClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListOrchestrationClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOrchestrationClusters",
        action: {
          (r: ListOrchestrationClustersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListOrchestrationClustersResponse
          in
          return try await self.inner.listOrchestrationClusters(request: r, options: o)
        })
    }

    public func getOrchestrationCluster(
      request: GetOrchestrationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.OrchestrationCluster {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOrchestrationCluster",
        action: {
          (r: GetOrchestrationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.OrchestrationCluster
          in
          return try await self.inner.getOrchestrationCluster(request: r, options: o)
        })
    }

    public func createOrchestrationCluster(
      request: CreateOrchestrationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createOrchestrationCluster",
        action: {
          (r: CreateOrchestrationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createOrchestrationCluster(request: r, options: o)
        })
    }

    public func deleteOrchestrationCluster(
      request: DeleteOrchestrationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOrchestrationCluster",
        action: {
          (r: DeleteOrchestrationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteOrchestrationCluster(request: r, options: o)
        })
    }

    public func listEdgeSlms(
      request: ListEdgeSlmsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListEdgeSlmsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEdgeSlms",
        action: {
          (r: ListEdgeSlmsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListEdgeSlmsResponse
          in
          return try await self.inner.listEdgeSlms(request: r, options: o)
        })
    }

    public func getEdgeSlm(
      request: GetEdgeSlmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.EdgeSlm {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEdgeSlm",
        action: {
          (r: GetEdgeSlmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.EdgeSlm
          in
          return try await self.inner.getEdgeSlm(request: r, options: o)
        })
    }

    public func createEdgeSlm(
      request: CreateEdgeSlmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEdgeSlm",
        action: {
          (r: CreateEdgeSlmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEdgeSlm(request: r, options: o)
        })
    }

    public func deleteEdgeSlm(
      request: DeleteEdgeSlmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEdgeSlm",
        action: {
          (r: DeleteEdgeSlmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteEdgeSlm(request: r, options: o)
        })
    }

    public func createBlueprint(
      request: CreateBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBlueprint",
        action: {
          (r: CreateBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Blueprint
          in
          return try await self.inner.createBlueprint(request: r, options: o)
        })
    }

    public func updateBlueprint(
      request: UpdateBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBlueprint",
        action: {
          (r: UpdateBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Blueprint
          in
          return try await self.inner.updateBlueprint(request: r, options: o)
        })
    }

    public func getBlueprint(
      request: GetBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBlueprint",
        action: {
          (r: GetBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Blueprint
          in
          return try await self.inner.getBlueprint(request: r, options: o)
        })
    }

    public func deleteBlueprint(
      request: DeleteBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBlueprint",
        action: { (r: DeleteBlueprintRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBlueprint(request: r, options: o)
        })
    }

    public func listBlueprints(
      request: ListBlueprintsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListBlueprintsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBlueprints",
        action: {
          (r: ListBlueprintsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListBlueprintsResponse
          in
          return try await self.inner.listBlueprints(request: r, options: o)
        })
    }

    public func approveBlueprint(
      request: ApproveBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "approveBlueprint",
        action: {
          (r: ApproveBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Blueprint
          in
          return try await self.inner.approveBlueprint(request: r, options: o)
        })
    }

    public func proposeBlueprint(
      request: ProposeBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "proposeBlueprint",
        action: {
          (r: ProposeBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Blueprint
          in
          return try await self.inner.proposeBlueprint(request: r, options: o)
        })
    }

    public func rejectBlueprint(
      request: RejectBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Blueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "rejectBlueprint",
        action: {
          (r: RejectBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Blueprint
          in
          return try await self.inner.rejectBlueprint(request: r, options: o)
        })
    }

    public func listBlueprintRevisions(
      request: ListBlueprintRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListBlueprintRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBlueprintRevisions",
        action: {
          (r: ListBlueprintRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListBlueprintRevisionsResponse
          in
          return try await self.inner.listBlueprintRevisions(request: r, options: o)
        })
    }

    public func searchBlueprintRevisions(
      request: SearchBlueprintRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.SearchBlueprintRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchBlueprintRevisions",
        action: {
          (r: SearchBlueprintRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.SearchBlueprintRevisionsResponse
          in
          return try await self.inner.searchBlueprintRevisions(request: r, options: o)
        })
    }

    public func searchDeploymentRevisions(
      request: SearchDeploymentRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.SearchDeploymentRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchDeploymentRevisions",
        action: {
          (r: SearchDeploymentRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.SearchDeploymentRevisionsResponse
          in
          return try await self.inner.searchDeploymentRevisions(request: r, options: o)
        })
    }

    public func discardBlueprintChanges(
      request: DiscardBlueprintChangesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.DiscardBlueprintChangesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "discardBlueprintChanges",
        action: {
          (r: DiscardBlueprintChangesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.DiscardBlueprintChangesResponse
          in
          return try await self.inner.discardBlueprintChanges(request: r, options: o)
        })
    }

    public func listPublicBlueprints(
      request: ListPublicBlueprintsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListPublicBlueprintsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPublicBlueprints",
        action: {
          (r: ListPublicBlueprintsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListPublicBlueprintsResponse
          in
          return try await self.inner.listPublicBlueprints(request: r, options: o)
        })
    }

    public func getPublicBlueprint(
      request: GetPublicBlueprintRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.PublicBlueprint {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPublicBlueprint",
        action: {
          (r: GetPublicBlueprintRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.PublicBlueprint
          in
          return try await self.inner.getPublicBlueprint(request: r, options: o)
        })
    }

    public func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDeployment",
        action: {
          (r: CreateDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Deployment
          in
          return try await self.inner.createDeployment(request: r, options: o)
        })
    }

    public func updateDeployment(
      request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDeployment",
        action: {
          (r: UpdateDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Deployment
          in
          return try await self.inner.updateDeployment(request: r, options: o)
        })
    }

    public func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDeployment",
        action: {
          (r: GetDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Deployment
          in
          return try await self.inner.getDeployment(request: r, options: o)
        })
    }

    public func removeDeployment(
      request: RemoveDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "removeDeployment",
        action: { (r: RemoveDeploymentRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.removeDeployment(request: r, options: o)
        })
    }

    public func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeployments",
        action: {
          (r: ListDeploymentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListDeploymentsResponse
          in
          return try await self.inner.listDeployments(request: r, options: o)
        })
    }

    public func listDeploymentRevisions(
      request: ListDeploymentRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListDeploymentRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeploymentRevisions",
        action: {
          (r: ListDeploymentRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListDeploymentRevisionsResponse
          in
          return try await self.inner.listDeploymentRevisions(request: r, options: o)
        })
    }

    public func discardDeploymentChanges(
      request: DiscardDeploymentChangesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.DiscardDeploymentChangesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "discardDeploymentChanges",
        action: {
          (r: DiscardDeploymentChangesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.DiscardDeploymentChangesResponse
          in
          return try await self.inner.discardDeploymentChanges(request: r, options: o)
        })
    }

    public func applyDeployment(
      request: ApplyDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "applyDeployment",
        action: {
          (r: ApplyDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Deployment
          in
          return try await self.inner.applyDeployment(request: r, options: o)
        })
    }

    public func computeDeploymentStatus(
      request: ComputeDeploymentStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ComputeDeploymentStatusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "computeDeploymentStatus",
        action: {
          (r: ComputeDeploymentStatusRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ComputeDeploymentStatusResponse
          in
          return try await self.inner.computeDeploymentStatus(request: r, options: o)
        })
    }

    public func rollbackDeployment(
      request: RollbackDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "rollbackDeployment",
        action: {
          (r: RollbackDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.Deployment
          in
          return try await self.inner.rollbackDeployment(request: r, options: o)
        })
    }

    public func getHydratedDeployment(
      request: GetHydratedDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.HydratedDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getHydratedDeployment",
        action: {
          (r: GetHydratedDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.HydratedDeployment
          in
          return try await self.inner.getHydratedDeployment(request: r, options: o)
        })
    }

    public func listHydratedDeployments(
      request: ListHydratedDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.ListHydratedDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listHydratedDeployments",
        action: {
          (r: ListHydratedDeploymentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.ListHydratedDeploymentsResponse
          in
          return try await self.inner.listHydratedDeployments(request: r, options: o)
        })
    }

    public func updateHydratedDeployment(
      request: UpdateHydratedDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.HydratedDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateHydratedDeployment",
        action: {
          (r: UpdateHydratedDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.HydratedDeployment
          in
          return try await self.inner.updateHydratedDeployment(request: r, options: o)
        })
    }

    public func applyHydratedDeployment(
      request: ApplyHydratedDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTelcoAutomationV1.HydratedDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "applyHydratedDeployment",
        action: {
          (r: ApplyHydratedDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTelcoAutomationV1.HydratedDeployment
          in
          return try await self.inner.applyHydratedDeployment(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
